kind = "web"
previewPath = "/"
title = "Saman's Barbershop"
version = "1.0.0"
id = "artifacts/samans-barbershop"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21952

[services.development]
run = "pnpm --filter @workspace/samans-barbershop run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/samans-barbershop", "run", "build" ]
publicDir = "artifacts/samans-barbershop/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21952"
BASE_PATH = "/"
